spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: http://localhost:8080/realms/Spring-Be/protocol/openid-connect/certs
#spring.security.oauth2.resourceserver.opaquetoken.client-id=springboot-be
#spring.security.oauth2.resourceserver.opaquetoken.client-secret=zfopel8nyMgZ4kpUADHxHOn6WI67Zurx
#spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=http://127.0.0.1:8081/realms/dive-dev/protocol/openid-connect/token/introspect

  swagger-ui:
    oauth:
      client-id: spring-be
springdoc:
  swagger-ui:
    oauth:
      client-secret: Gfk82ltV85omXMXjr3Fri4r1yJ03W21a
server:
    port: 8090

# application.yml
logging:
  level:
    org:
      springframework:
        security:  DEBUG
      keycloak: DEBUG

keycloak:
  realm: Spring-Be
  auth-server-url: http://localhost:8080/
  resource: spring-be
  credentials:
    secret: Gfk82ltV85omXMXjr3Fri4r1yJ03W21a
  policy-enforcer-config:
    enforcement-mode: DISABLED
    paths:
      - path: /swagger-ui.html
      - path: /error

realm : Spring-Be
server-url : http://localhost:8080/
client-id : admin-cli
grant-type : password
name : quochuy
password : 123